name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # Set this to your default branch
  workflow_dispatch:  # Allow manual triggers

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
    
    - name: Prepare deployment package
      run: |
        mkdir -p deploy
        # Copy only necessary files (exclude node_modules, source files, tests, etc.)
        cp -r dist package.json azure-startup.js .deployment web.config deploy/
        # Create a slim version of node_modules with only production dependencies
        cd deploy
        npm ci --production --no-optional
        cd ..
    
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'seapp'  # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './deploy'
        
    - name: Post deployment cleanup
      run: rm -rf deploy